// packages/vue/src/Dialog.vue
<script setup lang="ts">
const emit = defineEmits(["onClose", "onClickInside"])
const onClose = () => {
  emit("onClose")
}

const onClickInside = (e) => {
  e.stopPropagation()
  emit("onClickInside")
}
</script>

<template>
  <div @click="onClose" class="dialog-styles">
    <div @click="onClickInside" class="dialog-container">
      <slot />
    </div>
  </div>
</template>

// react/Dialog.tsx
import React from "react"

const Dialog = ({
                  onClose = () => {
                  },
                  children,
                  ...props
                }) => {

  const onClickInside = (e) => {
    e.stopPropagation()
  }

  return (
    <div onClick={onClose} className="dialog-styles">
      <div onClick={onClickInside} className="dialog-container">
        {children}
      </div>
    </div>
  )
}

export default Dialog
