// svelte/buttons/IIButton.svelte
<script lang="ts">
  import dfinityLogo from "../../assets/dfinity.svg"
  import "../../connect2ic.css"

  export let dark = false
</script>

<button on:click class={"button-styles ii-styles"} style={dark ? `` : `background: #f4f4f4; color: black;`}>
  <img style="width: 55px;" class={"img-styles"} src={dfinityLogo} />
  <div>
    <span class="button-label">
      Internet Identity
    </span>
    <span>
    Connect with your Internet Identity
    </span>
  </div>
</button>

// react/buttons/IIButton.tsx
import React from "react"
import dfinityLogo from "../../assets/dfinity.svg"
import "../../connect2ic.css"

const IIButton = ({ dark = false, ...props }) => {
  return (
    <button className="button-styles ii-styles"
            style={dark ? {} : { background: "#f4f4f4", color: "black" }} {...props}>
      <img style={{ width: "55px" }} className={"img-styles"} src={dfinityLogo} />
      <div>
        <span className="button-label">Internet Identity</span>
        <span>Connect with your Internet Identity</span>
      </div>
    </button>
  )
}

export default IIButton
