// packages/svelte/src/components/ConnectDialog.svelte
<script lang="ts">
  import { useConnect, useDialog, useProviders } from "../stores/index.ts"
  import { onMount } from "svelte"

  export let onClose: () => void = () => {
    close()
  }
  export let dark: boolean = false

  const onClickInside = (e) => {
    e.stopPropagation()
  }

  const { isOpen, close, open } = useDialog()
  const providers = useProviders()
  const { connect } = useConnect({
    onConnect: () => {
      close()
    },
  })

  if ($isOpen) {
    document.body.style.overflow = "hidden"
  }
  if (!$isOpen) {
    document.body.style.overflow = "unset"
  }

  onMount(() => {
    const handleEsc = (event) => {
      if (event.keyCode === 27) {
        close()
      }
    }
    window.addEventListener("keydown", handleEsc)
    return () => {
      window.removeEventListener("keydown", handleEsc)
    }
  })

</script>

{#if $isOpen}
  <div class={`dialog-styles ${dark ? "dark" : "light"}`} on:click={onClose}>
    <div on:click={onClickInside} class="dialog-container">
      <div>
        {#each $providers as provider}
          <button key={provider.meta.id} on:click={() => connect(provider.meta.id)}
                  class={`button-styles ${provider.meta.id}-styles`}>
            <img class={"img-styles"} src={dark ? provider.meta.icon.dark : provider.meta.icon.light} />
            <div>
              <span class="button-label">{provider.meta.name}</span>
            </div>
          </button>
        {/each}
      </div>
    </div>
  </div>
{/if}

// packages/react/src/components/ConnectDialog.tsx
import React, { PropsWithChildren, useEffect } from "react"
import { useDialog } from "../hooks"
import { useProviders } from "../hooks"
import { useConnect } from "../hooks"

type Props = {
  onClose?: () => void
  dark?: boolean
}

const ConnectDialog: React.FC<PropsWithChildren<Props>> = (props) => {
  const {
    onClose = () => {
      dialog.close()
    },
    children,
    dark,
  } = props

  const dialog = useDialog()
  const providers = useProviders()

  const { connect, isConnected } = useConnect()

  useEffect(() => {
    if (isConnected) {
      dialog.close()
    }
  }, [isConnected])

  useEffect(() => {
    if (dialog.isOpen) {
      document.body.style.overflow = "hidden"
    }
    if (!dialog.isOpen) {
      document.body.style.overflow = "unset"
    }
  }, [dialog.isOpen])

  useEffect(() => {
    const handleEsc = (event) => {
      if (event.keyCode === 27) {
        dialog.close()
      }
    }
    window.addEventListener("keydown", handleEsc)

    return () => {
      window.removeEventListener("keydown", handleEsc)
    }
  }, [])

  const onClickInside = (e) => {
    e.stopPropagation()
  }

  return dialog.isOpen ? (
    <>
      <div className={`dialog-styles ${dark ? "dark" : "light"}`} onClick={onClose}>
        <div onClick={onClickInside} className="dialog-container">
          <div>
            {providers.map((provider) => {
              return (
                <button key={provider.meta.id} onClick={() => connect(provider.meta.id)}
                        className={`button-styles ${provider.meta.id}-styles`} {...props}>
                  <img className={"img-styles"} src={dark ? provider.meta.icon.dark : provider.meta.icon.light} />
                  <div>
                    <span className="button-label">{provider.meta.name}</span>
                  </div>
                </button>
              )
            })}
          </div>
        </div>
      </div>
    </>
  ) : null
}

export default ConnectDialog
