// svelte/buttons/MetamaskButton.svelte
<script lang="ts">
  import MetamaskLogo from "../../assets/metamask-fox.svg"
  import "../../connect2ic.css"
  export let dark = false
</script>

<button on:click class={"button-styles metamask-styles"} style={dark ? `` : `background: #f4f4f4; color: black;`}>
  <img class={"img-styles"} src={MetamaskLogo} />
  <div>
  <span class="button-label">
  Metamask
  </span>
    <span>
    Connect with your Metamask wallet
    </span>
  </div>
</button>

// vue/buttons/MetamaskButton.vue
<script setup lang="ts">
import metamaskLogo from "../../assets/metamask-fox.svg"
import "../../connect2ic.css"

const props = defineProps({
  dark: {
    type: Boolean,
    default: false,
  },
})
</script>

<template>
  <button class="button-styles metamask-styles" :style="dark ? `` : `background: #f4f4f4; color: black;`">
    <img class="img-styles" :src="metamaskLogo" />
    <div>
    <span class="button-label">
      Metamask
    </span>
      <span>
    Connect with your Metamask wallet
    </span>
    </div>
  </button>
</template>
