// react/Connect.tsx
import React, { useEffect, useState } from "react"
import {
  Dialog,
  IIButton,
  StoicButton,
  PlugButton,
  MetamaskButton,
  useAuth,
} from "./"

const Connect = (props) => {
  const {
    config = {
      ii: {},
      plug: {},
      stoic: {},
      metamask: {},
    },
    style = {},
    dark = false,
    onConnect = () => {
    },
    onDisconnect = () => {
    },
  } = props

  const auth = useAuth({
    onConnect,
    onDisconnect,
  })
  const [showDialog, setShowDialog] = useState(false)

  useEffect(() => {
    if (auth.status === "connected") {
      setShowDialog(false)
    }
  }, [auth.status])

  return (
    <>
      {auth.status === "connected" ? (
        <button style={style} className="connect-button" onClick={() => auth.disconnect()}>
          Disconnect
        </button>
      ) : null}

      {auth.status !== "connected" ? (
        <button style={style} className="connect-button" onClick={() => setShowDialog(true)}>
          Connect
        </button>
      ) : null}

      {showDialog ? (
        <Dialog onClose={() => setShowDialog(false)}>
          <IIButton onClick={() => auth.connect("ii")} dark={dark} />
          <StoicButton onClick={() => auth.connect("stoic")} dark={dark} />
          <PlugButton onClick={() => auth.connect("plug")} dark={dark} />
          <MetamaskButton onClick={() => auth.connect("metamask")} dark={dark} />
        </Dialog>
      ) : null}
    </>
  )
}

export default Connect

// svelte/Connect.svelte
<script>
  import {
    Dialog,
    IIButton,
    StoicButton,
    PlugButton,
    MetamaskButton,
    createAuth,
  } from "./"

  export let onConnect = (connection) => {
  }
  export let onDisconnect = () => {
  }
  export let dark = false
  export let style = ""
  export let config = {
    ii: {},
    plug: {},
    stoic: {},
    metamask: {},
  }

  let auth = createAuth({
    // providers,
    onConnect,
    onDisconnect,
  })

  let showDialog = false
  $: if ($auth.status === "connected") {
    showDialog = false
  }
</script>

{#if $auth.status === "connected"}
  <button style={style} class="connect-button" on:click={() => auth.disconnect()}>
    Disconnect
  </button>
{/if}

{#if $auth.status !== "connected"}
  <button style={style} class="connect-button" on:click={() => showDialog = true}>
    Connect
  </button>
{/if}

{#if showDialog}
  <Dialog onClose={() => showDialog = false}>
    <IIButton on:click={() => auth.connect("ii")} dark={dark} />
    <StoicButton on:click={() => auth.connect("stoic")} dark={dark} />
    <PlugButton on:click={() => auth.connect("plug")} dark={dark} />
    <MetamaskButton on:click={() => auth.connect("metamask")} dark={dark} />
  </Dialog>
{/if}
