// packages/svelte/src/components/ConnectButton.svelte
<script lang="ts">
  import { useConnect, useDialog } from "../stores/index.ts"

  export const onConnect: () => void = () => {
  }
  export const onDisconnect: () => void = () => {
  }
  export const dark: boolean = false
  export const style: string = ""

  const { open } = useDialog()
  const { isConnected, disconnect } = useConnect({
    onConnect,
    onDisconnect,
  })
</script>

{#if $isConnected}
  <button style={style} class="connect-button" on:click={() => disconnect()}>
    Disconnect
  </button>
{/if}

{#if !$isConnected}
  <button style={style} class="connect-button" on:click={() => open()}>
    Connect
  </button>
{/if}

// packages/react/components/ConnectButton.tsx
import React, { useEffect, useState } from "react"
import {
  useConnect, useDialog,
} from "../index"

const ConnectButton = (props) => {
  const {
    style = {},
    dark = false,
    onConnect = () => {
    },
    onDisconnect = () => {
    },
    children,
  } = props

  const dialog = useDialog()
  const { disconnect, isConnected } = useConnect({
    onConnect,
    onDisconnect,
  })

  return (
    <>
      {!isConnected ? (
        <button onClick={() => dialog.open()} style={style} className="connect-button">
          {children ?? "Connect"}
        </button>
      ) : null}
      {isConnected ? (
        <button onClick={disconnect} style={style} className="connect-button">
          {children ?? "Disconnect"}
        </button>
      ) : null}
    </>
  )
}

export default ConnectButton
