// examples/react/frontend/App.tsx
import React from "react"
import { Counter } from "./components/Counter"
import { Transfer } from "./components/Transfer"
import { Profile } from "./components/Profile"
import logo from "./assets/dfinity.svg"
import * as counter from "canisters/counter"

import { createClient } from "@connect2ic/core"
import { defaultProviders } from "@connect2ic/core/providers"
import { ConnectButton, ConnectDialog, Connect2ICProvider, useConnect } from "@connect2ic/react"
import "@connect2ic/core/style.css"

function App() {

  const { principal } = useConnect()

  return (
    <div className="App">
      <div className="auth-section">
        <ConnectButton />
      </div>
      <ConnectDialog />

      <h1>{principal}</h1>

      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p className="slogan">
          React+TypeScript Template
        </p>
        <p className="twitter">by <a href="https://twitter.com/miamaruq">@miamaruq</a></p>
      </header>

      <p className="examples-title">
        Examples
      </p>
      <div className="examples">
        <Counter />
        <Profile />
        <Transfer />
      </div>

    </div>
  )
}

const client = createClient({
  canisters: {
    counter,
  },
  providers: defaultProviders,
  globalProviderConfig: {
    dev: import.meta.env.DEV,
  },
})

export default () => (
  <Connect2ICProvider client={client}>
    <App />
  </Connect2ICProvider>
)

// examples/vue/frontend/App.vue
<script setup lang="ts">
import * as counter from "../.dfx/local/canisters/counter"
import Counter from "./components/Counter.vue"
import Profile from "./components/Profile.vue"
import Transfer from "./components/Transfer.vue"
import logo from "./assets/dfinity.svg"
import { defaultProviders } from "@connect2ic/core/providers"
import { createClient } from "@connect2ic/core"
import { ConnectButton, ConnectDialog, Connect2ICProvider } from "@connect2ic/vue"
import "@connect2ic/core/style.css"

const client = createClient({
  canisters: {
    counter,
  },
  providers: defaultProviders,
  globalProviderConfig: {
    dev: import.meta.env.DEV,
  },
})
</script>

<template>
  <Connect2ICProvider :client="client">
    <div class="App">
      <div class="auth-section">
        <ConnectButton />
      </div>
      <ConnectDialog />
      <header class="App-header">
        <img :src="logo" class="App-logo" alt="logo" />
        <p class="slogan">
          Vue+TypeScript Template
        </p>
        <p class="twitter">by <a href="https://twitter.com/miamaruq">@miamaruq</a></p>
      </header>

      <p class="examples-title">
        Examples
      </p>
      <div class="examples">
        <Counter />
        <Profile />
        <Transfer />
      </div>
    </div>
  </Connect2ICProvider>
</template>

<style>
body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
  "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
  sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #424242;
}

button {
  font-weight: 600;
}

.slogan {
  font-size: 1.7em;
  margin-bottom: 0;
}

.twitter {
  font-size: 0.4em;
}

.App-logo {
  height: 14vmin;
  pointer-events: none;
  transform: scale(1);
  animation: pulse 3s infinite;
}

.App-header {
  height: calc(100vh - 70px);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
}

.examples {
  padding: 30px 100px;
  display: grid;
  grid-gap: 30px;
  grid-template-columns: 1fr 1fr 1fr;
}

.examples-title {
  font-Size: 1.3em;
  margin-bottom: 0;
  text-align: center;
}

.example {
  padding: 50px 50px;
  min-height: 300px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  /*border: 1px solid black;*/
  /*background: #f4f4f4;*/
  border-radius: 15px;
}

.example-disabled {
  font-size: 1.3em;
  color: #9e9e9e;
}

.demo-button {
  background: #a02480;
  padding: 0 1.3em;
  margin-top: 1em;
  border-radius: 60px;
  font-size: 0.7em;
  height: 35px;
  outline: 0;
  border: 0;
  cursor: pointer;
  color: white;
}

.demo-button:active {
  color: white;
  background: #979799;
}

.auth-section {
  padding: 1em;
  display: flex;
  justify-content: flex-end;
  align-items: center;
  text-align: right;
  position: fixed;
  top: 0;
  right: 0;
}

@keyframes pulse {
  0% {
    transform: scale(0.97);
    opacity: 0;
  }

  70% {
    transform: scale(1);
    opacity: 1;
  }

  100% {
    transform: scale(0.97);
    opacity: 0;
  }
}
</style>
